#!/bin/sh
# this script exports the Infinality environment variables to the environment
# controlled through launchctl (LaunchServices), and accessible to all apps
# on Mac OS X.

if [ -n "${INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH}" ] ;then
	launchctl setenv INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH "${INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH}"
else
	launchctl unsetenv INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH
fi

if [ -n "${INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS}" ] ;then
	launchctl setenv INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS "${INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS}"
else
	launchctl unsetenv INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS
fi

if [ -n "${INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT}" ] ;then
	launchctl setenv INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT "${INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT}"
else
	launchctl unsetenv INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT
fi

if [ -n "${INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH}" ] ;then
	launchctl setenv INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH "${INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH}"
else
	launchctl unsetenv INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH
fi

if [ -n "${INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE}" ] ;then
	launchctl setenv INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE "${INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE}"
else
	launchctl unsetenv INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE
fi

if [ -n "${INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE}" ] ;then
	launchctl setenv INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE "${INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE}"
else
	launchctl unsetenv INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE
fi

if [ -n "${INFINALITY_FT_BRIGHTNESS}" ] ;then
	launchctl setenv INFINALITY_FT_BRIGHTNESS "${INFINALITY_FT_BRIGHTNESS}"
else
	launchctl unsetenv INFINALITY_FT_BRIGHTNESS
fi

if [ -n "${INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH}" ] ;then
	launchctl setenv INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH "${INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH}"
else
	launchctl unsetenv INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH
fi

if [ -n "${INFINALITY_FT_CONTRAST}" ] ;then
	launchctl setenv INFINALITY_FT_CONTRAST "${INFINALITY_FT_CONTRAST}"
else
	launchctl unsetenv INFINALITY_FT_CONTRAST
fi

if [ -n "${INFINALITY_FT_FILTER_PARAMS}" ] ;then
	launchctl setenv INFINALITY_FT_FILTER_PARAMS "${INFINALITY_FT_FILTER_PARAMS}"
else
	launchctl unsetenv INFINALITY_FT_FILTER_PARAMS
fi

if [ -n "${INFINALITY_FT_FRINGE_FILTER_STRENGTH}" ] ;then
	launchctl setenv INFINALITY_FT_FRINGE_FILTER_STRENGTH "${INFINALITY_FT_FRINGE_FILTER_STRENGTH}"
else
	launchctl unsetenv INFINALITY_FT_FRINGE_FILTER_STRENGTH
fi

if [ -n "${INFINALITY_FT_GAMMA_CORRECTION}" ] ;then
	launchctl setenv INFINALITY_FT_GAMMA_CORRECTION "${INFINALITY_FT_GAMMA_CORRECTION}"
else
	launchctl unsetenv INFINALITY_FT_GAMMA_CORRECTION
fi

if [ -n "${INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE}" ] ;then
	launchctl setenv INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE "${INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE}"
else
	launchctl unsetenv INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE
fi

if [ -n "${INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE}" ] ;then
	launchctl setenv INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE "${INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE}"
else
	launchctl unsetenv INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE
fi

if [ -n "${INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH}" ] ;then
	launchctl setenv INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH "${INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH}"
else
	launchctl unsetenv INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH
fi

if [ -n "${INFINALITY_FT_STEM_ALIGNMENT_STRENGTH}" ] ;then
	launchctl setenv INFINALITY_FT_STEM_ALIGNMENT_STRENGTH "${INFINALITY_FT_STEM_ALIGNMENT_STRENGTH}"
else
	launchctl unsetenv INFINALITY_FT_STEM_ALIGNMENT_STRENGTH
fi

if [ -n "${INFINALITY_FT_STEM_FITTING_STRENGTH}" ] ;then
	launchctl setenv INFINALITY_FT_STEM_FITTING_STRENGTH "${INFINALITY_FT_STEM_FITTING_STRENGTH}"
else
	launchctl unsetenv INFINALITY_FT_STEM_FITTING_STRENGTH
fi

if [ -n "${INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE}" ] ;then
	launchctl setenv INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE "${INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE}"
else
	launchctl unsetenv INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE
fi

if [ -n "${INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS}" ] ;then
	launchctl setenv INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS "${INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS}"
else
	launchctl unsetenv INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS
fi

if [ -n "${INFINALITY_FT_USE_VARIOUS_TWEAKS}" ] ;then
	launchctl setenv INFINALITY_FT_USE_VARIOUS_TWEAKS "${INFINALITY_FT_USE_VARIOUS_TWEAKS}"
else
	launchctl unsetenv INFINALITY_FT_USE_VARIOUS_TWEAKS
fi

if [ -n "${INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH}" ] ;then
	launchctl setenv INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH "${INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH}"
else
	launchctl unsetenv INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH
fi

if [ -n "${PANGOCAIRO_BACKEND}" ] ;then
	launchctl setenv PANGOCAIRO_BACKEND "${PANGOCAIRO_BACKEND}"
else
	launchctl unsetenv PANGOCAIRO_BACKEND
fi
