#!/bin/bash

print_usage () {
    cat <<- ENDUSAGE
    #> cmake2port [cmake options] [port options] [--] [port options]
    cmake2-port options (NB no '=' between option and argument!):
        --port portName
        --variants variant(s)
        --configure.optflags "compiler options"
        --rewind : force a repeat of the port configure phase
    A wrapper that takes a CMake commandline and tries to convert it to a MacPorts port call
    Known CMake options are filtered out until a lone '--' option is encountered
    The port name has to be specified with "--port foo"
    Variant(s) can be specified with the --variants option.
ENDUSAGE
}

PORTOPTIONS=""
PORTOTHEROPTIONS=""
PORT=""
VARIANTS=""
REWIND=0
NOMORECMAKEOPTIONS=0
ECHO=""
OPTFLAGS=""

OPTSHIFT=0
parse_portOptions () {
    OPTSHIFT=0
    case $1 in
        --rewind)
            REWIND=1
            ;;
        --port)
            PORT="$2"
            OPTSHIFT=1
            ;;
        --variants)
            VARIANTS="${VARIANTS}$2"
            OPTSHIFT=1
            ;;
        --configure.optflags)
            if [ "${OPTFLAGS}" != "" ] ;then
                OPTFLAGS="${OPTFLAGS} ${2}"
            else
                OPTFLAGS="${2}"
            fi
            OPTSHIFT=1
            ;;
        -*)
            PORTOPTIONS="${PORTOPTIONS} $1"
            ;;
        configure.*)
            PORTOTHEROPTIONS="${PORTOTHEROPTIONS} $1"
            ;;
        *)
            PORTOTHEROPTIONS="${PORTOTHEROPTIONS} \"$1\""
            ;;
    esac
}

while [ $# != 0 ] ;do
    if [ ${NOMORECMAKEOPTIONS} = 0 ] ;then
        case $1 in
            --dryrun)
                ECHO="echo"
                ;;
            -D|-C|-U|-G|-T|-P|--build|--system-information)
                # cmake options taking an argument
                shift
                ;;
            -E|-Wno-dev|-Wdev|-L*|-N|--find-package|--graphviz*|--help*)
                ;;
            -D*)
                # cmake option setting a variable (e.g. -DCMAKE_BUILD_TYPE=foo)
                ;;
            --)
                NOMORECMAKEOPTIONS=1
                ;;
            *)
                if [ ! -d "${1}" ] ;then
                    parse_portOptions "$@"
                    shift ${OPTSHIFT}
                else
                    echo "Skipping \"${1}\"; probably pointing cmake to the source or build directory" 1>&2
                fi
                ;;
        esac
    else
        parse_portOptions "$@"
        shift ${OPTSHIFT}
    fi
    shift
done

if [ "${PORT}" != "" ] ;then
    if [ ${REWIND} = 1 ] ;then
        ${ECHO} port-redo-install-phase -configure ${PORT}
    fi
    set -x
    if [ "${OPTFLAGS}" != "" ] ;then
        ${ECHO} port ${PORTOPTIONS} configure ${PORT} ${VARIANTS} ${PORTOTHEROPTIONS} configure.optflags="${OPTFLAGS}"
    else
        ${ECHO} port ${PORTOPTIONS} configure ${PORT} ${VARIANTS} ${PORTOTHEROPTIONS}
    fi
    RET=$?
    if [ ${RET} = 0 ] ;then
        WDIR="`port work ${PORT}`"
        if [ -d ${WDIR}/build ] ;then
            touch ${WDIR}/build/compile_commands.json
        fi
    fi
    exit ${RET}
else
    print_usage
fi
