#!/bin/sh

HELPCOLLECTION=""
QMAKE="@QTBINDIR@/qmake"

if [ -x ${QMAKE} ] ;then
    QTDIR="`${QMAKE} -query QT_INSTALL_PREFIX`"
    if [ -e ${QTDIR}/share/doc/qt5/MP-qthelp-collection.qhc ] ;then
        HELPCOLLECTION="-collectionFile $QTDIR/share/doc/qt5/MP-qthelp-collection.qhc"
    fi
    QTBINDIR="`${QMAKE} -query QT_INSTALL_BINS`"
fi

if [ "`which assistant-qt5`" != "" ] ;then
    exec assistant-qt5 $HELPCOLLECTION "$@"
else
    exec ${QTBINDIR}/assistant $HELPCOLLECTION "$@"
fi
