#!/bin/sh

HELPCOLLECTION=""

if [ "`which qmake-qt5`" != "" ] ;then
    QTDIR="`qmake-qt5 -query QT_INSTALL_PREFIX`"
    if [ -e $QTDIR/share/doc/qch/MP-qthelp-collection.qhc ] ;then
        HELPCOLLECTION="-collectionFile $QTDIR/share/doc/qch/MP-qthelp-collection.qhc"
    fi
fi

exec assistant-qt5 $HELPCOLLECTION "$@"
