#!/bin/sh

HELPCOLLECTION=""
if [ "${QTBINDIR}" != "" ] ;then
	QMAKE="${QTBINDIR}/qmake"
else
	QMAKE="@QTBINDIR@/qmake"
	if [ "`which assistant-qt5`" != "" ] ;then
	    # in this case we can go through the installed app-wrapper
	    ASSISTANT=assistant-qt5
	fi
fi

if [ -x ${QMAKE} ] ;then
    QTDIR="`${QMAKE} -query QT_INSTALL_PREFIX`"
    if [ -e ${QTDIR}/share/doc/qt5/MP-qthelp-collection.qhc ] ;then
        HELPCOLLECTION="-collectionFile $QTDIR/share/doc/qt5/MP-qthelp-collection.qhc"
    fi
    QTBINDIR="`${QMAKE} -query QT_INSTALL_BINS`"
fi

export QT_MAC_FONTENGINE=CoreText

if [ "${ASSISTANT}" != "" ] ;then
    exec ${ASSISTANT} $HELPCOLLECTION "$@"
else
    exec ${QTBINDIR}/assistant $HELPCOLLECTION "$@"
fi
