#!/bin/sh

cd
if [ -d .cache/kdevduchain/ ] ;then
    cd .cache/kdevduchain
    if [ "$1" = "lock" ] ;then
        for t in ./*/topcontexts ;do
            rm -f ${t}/*
            chmod -w ${t}
        done
        shift 1
    else
        rm -rf ./*/topcontexts
    fi
    if [ "`which afsctool`" != "" ];then
        if [ $# = 0 ] ;then
            afsctool -cfvv -J8 -8 -S -R8 "$@" ./*
        else
            afsctool -c "$@" ./*
        fi
    fi
fi
